//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamados
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }

    }
}
